### ISSUE TITLE
search option breaking the menu

### ISSUE THREAD

**Issue by SKITTLE6969** [alberttheprince/rpemotes-reborn#11]
open search menu and search for an emote and hit enter
![image](https://github.com/user-attachments/assets/4f00bdb9-0a75-4bf0-8fb5-ddf102265ae4)

**Comment by alberttheprince** [comment]
Fix has been pushed to main branch, please test so we can confirm this is fixed.  @SKITTLE6969

**Comment by alberttheprince** [comment]
Issue fixed in latest, 1.5.5 republished
