### ISSUE TITLE
[BUG] LocalPlayer state canEmote doesn't work at all 

### ISSUE THREAD

**Issue by iSentrie** [alberttheprince/rpemotes-reborn#23]
This part doesn't work at all.
```lua
LocalPlayer.state:set('canEmote', false, true) -- stops emoting
LocalPlayer.state:set('canEmote', true, true) -- allows emoting
```

**Comment by alberttheprince** [comment]
Hmm, looks like this was removed in the big PR before - I'll need to look through our older version of rpemotes-reborn and read it.

**Comment by iSentrie** [comment]
> Hmm, looks like this was removed in the big PR before - I'll need to look through our older version of rpemotes-reborn and read it.

share link if u'll find

**Comment by alberttheprince** [comment]
Can you test the main branch? I've fixed it, just test if it all works.

**Comment by iSentrie** [comment]
Maybe should add to crouch / crawl too #25

**Comment by iSentrie** [comment]
> Can you test the main branch? I've fixed it, just test if it all works.

Players cannot emote at all now.
Also maybe should add to crouch / crawl too #25

**Comment by alberttheprince** [comment]
Thanks for your fixes, they've been merged.
