### ISSUE TITLE
[request] Disable crouch/crawl entirely

### ISSUE THREAD

**Issue by keiraskyler** [alberttheprince/rpemotes-reborn#25]
**Describe the Feature**
A way to completely disable the crouch/crawl feature in the server temporarily, with the /crouch /crawl commands to disable these from happening when pressing their keybinds.

**Example/Mock up**
Type /crouch or /crawl into the text box as a command and then the player cannot crouch or crawl until the command is toggled back on to enable crouch or crawl.

If some other way to disable it would work better I'd be happy for that too this is just a suggestion as I have completely unbound stealth mode and crouch and crawl and still crouch or crawl with the keybinds.

**Comment by iSentrie** [comment]
You unbound them and they still actively working?

**Comment by alberttheprince** [comment]
@iSentrie I think Keira is looking for a way to have a crouch/crawl lock out keybind, while still having crouch available. 

i.e. 

You can crouch, but if you type /crouchtoggle you can't crouch until typing /crouchtoggle again. As it is, crouching does not work if you set it as false in the config. 

I'm not sure the use case for this, @keiraskyler would you be able to explain where this would be useful to have? Are there times when you press crouch and you don't want to crouch?

**Comment by keiraskyler** [comment]
Yes exactly correct!!Sent from my iPhoneOn Aug 2, 2024, at 2:32 PM, Popcorn RP - PrinceAlbert ***@***.***> wrote:﻿
@iSentrie I think Keira is looking for a way to have a crouch/crawl lock out keybind, while still having crouch available.
i.e.
You can crouch, but if you type /crouchtoggle you can't crouch until typing /crouchtoggle again. As it is, crouching does not work if you set it as false in the config.
I'm not sure the use case for this, @keiraskyler would you be able to explain where this would be useful to have? Are there times when you press crouch and you don't want to crouch?

**Comment by keiraskyler** [comment]
When currently using freecam and taking screenshots for the server ctrl is a main key for camera functions that can’t be rebound and it makes the character move when you don’t want it to moveSent from my iPhoneOn Aug 2, 2024, at 2:32 PM, Popcorn RP - PrinceAlbert ***@***.***> wrote:﻿
@iSentrie I think Keira is looking for a way to have a crouch/crawl lock out keybind, while still having crouch available.
i.e.
You can crouch, but if you type /crouchtoggle you can't crouch until typing /crouchtoggle again. As it is, crouching does not work if you set it as false in the config.
I'm not sure the use case for this, @keiraskyler would you be able to explain where this would be useful to have? Are there times when you press crouch and you don't want to crouch?

**Comment by iSentrie** [comment]
now that's a mess to read, ill skip this

**Comment by alberttheprince** [comment]
Cleaned up Keira's comments, assume github email formatting was messing it up.

**Comment by alberttheprince** [comment]
I've contacted the original creator of the code dealing with crouching, will ask if that's something he's interested in adding.

**Comment by iSentrie** [comment]
It's just 1 ore more lines of code, i don't see any use for this for majority, server dev's can adjust this themselfs.

**Comment by alberttheprince** [comment]
Sure, we'll leave this open for anyone interested in adding that + a line to the config. This is the crouch/crawl resource originally added to rpemotes, but it seems to have been improved since it was added:

https://github.com/MadsLeander/crouch_crawl

**Comment by iSentrie** [comment]
> Sure, we'll leave this open for anyone interested in adding that + a line to the config. This is the crouch/crawl resource originally added to rpemotes, but it seems to have been improved since it was added:
> 
> https://github.com/MadsLeander/crouch_crawl

his case is actually covered by use of, no need to keep it open since state is now fully working, he has to change states between his freecam toggles
```lua
LocalPlayer.state:set('canEmote', false, true) -- stops emoting
LocalPlayer.state:set('canEmote', true, true) -- allows emoting
```

**Comment by alberttheprince** [comment]
@keiraskyler If you can edit your resource, this would probably be the right way to use this.

**Comment by iSentrie** [comment]
Closing because of no response. Script already has functionality for your needs.

**Comment by keiraskyler** [comment]
Currently been dealing with a hurricane and flooding. Apologies for only being able to email!

**Comment by iSentrie** [comment]
> Currently been dealing with a hurricane and flooding. Apologies for only being able to email!

Sorry to hear that, however solution is this
```lua
LocalPlayer.state:set('canEmote', false, true) -- stops emoting
LocalPlayer.state:set('canEmote', true, true) -- allows emoting
```
