### ISSUE TITLE
1.6.3 error

### ISSUE THREAD

**Issue by theevelynnprivate** [alberttheprince/rpemotes-reborn#29]
**Describe the bug**
You can't open emote menu and do emotes because emote.lua doesn't run.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install 1.6.3

**Expected behaviour**
Menu should open and emotes should work

**Additional context**
Error is attached, my server doesn't have any other emotemenus or anything that could possiby interfere with the script. Its a localhost.

![image](https://github.com/user-attachments/assets/2ff9654f-e0eb-4477-8311-12f8310ade46)

**Comment by alberttheprince** [comment]
This should be fixed

**Comment by iSentrie** [comment]
eh my pr's :(

**Comment by iSentrie** [comment]
btw, these new emotes require build 3258+

**Comment by alberttheprince** [comment]
> btw, these new emotes require build 3258+

How should we indicate this?

**Comment by alberttheprince** [comment]
Closing this as the problem was me forgetting to put , after some anim dictionaries.
