### ISSUE TITLE
Latest Release still broken.

### ISSUE THREAD

**Issue by MerlinisaG** [alberttheprince/rpemotes-reborn#36]
**Describe the bug**
The same issue persists on Latest Release '1.6.3' Missing commas and in the fxmanifest the version shows as '1.6.2'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on latest release '1.6.3'.
2. Install and restart resource or server.
3. Same errors as before.

**Expected behaviour**
A "Latest Release" should not be broken like this, especially after being "fixed" already for the same issue.
**Additional context**
I do see it is fixed in further commits, but again... in the current "Latest Release", this should not persist. Maybe master branches, but latest release should be used for ready for production.

**Comment by alberttheprince** [comment]
I'll republish this - it should be fixed as we re-released 1.6.3. 

For future reference, please share specific error messages, an image, etc. so we can at least know if this is a new or old error/issue.

**Comment by alberttheprince** [comment]
1.6.5 released with everything fixed, sorry about that!

**Comment by MerlinisaG** [comment]
Yeah no problem I just figured since it was the same exact commas missing and same exact issue with the fxmanifest that you would know what it was. Thank you for your time.
