### ISSUE TITLE
Adult Emotes

### ISSUE THREAD

**Issue by broonib** [alberttheprince/rpemotes-reborn#43]
**Describe the bug**
There are still shared Adult emotes available even after you disable emotes within the config.

**Comment by alberttheprince** [comment]
Are all of them available? Or only some? Please list which ones are available, they may need tagging.

**Comment by broonib** [comment]
Toop of my head

Give and Receive Blowjob
F Sex Pose 1, 2 3
Street Sex Male and Female
Jerkoff Female
Wank 1 2 3 4 5

**Comment by alberttheprince** [comment]
Are you using the latest rpemotes, have you updated your animation list? This is working for me.

![image](https://github.com/user-attachments/assets/0628c4e4-0d83-4163-8594-45ede8341e18)
![image](https://github.com/user-attachments/assets/c933619d-f36b-4881-92ef-bff572fa8d58)

**Comment by broonib** [comment]
All sorted it didnt push my changes lol Thank you
