### ISSUE TITLE
Issues with hands Up

### ISSUE THREAD

**Issue by broonib** [alberttheprince/rpemotes-reborn#45]
We are having issues with people using hands up, Our current hands up is controlled by QS inventory with yours as disabled.

However if someone put their hands up they cant put them down, Its not everyone but most. If I stop RP emotes it works as it should.

**Comment by iSentrie** [comment]
So you are using 2 different hands up scripts and you expect them to work together? Disable one.

**Comment by alberttheprince** [comment]
> So you are using 2 different hands up scripts and you expect them to work together? Disable one.

I think OP is saying that with ours disabled in the config, it's still working.

**Comment by alberttheprince** [comment]
-- Hands Up Options
    HandsupEnabled = false, -- You can disable the handsup here / change the keybind. It is currently set to Y
    HandsupKeybind = 'Y', -- Get the button string here https://docs.fivem.net/docs/game-references/input-mapper-parameter-ids/keyboard/
    HandsupKeybindEnabled = false,
    HandsupKeybindInCarEnabled = false,


Is your config set like this?

**Comment by broonib** [comment]
> So you are using 2 different hands up scripts and you expect them to work together? Disable one.

As said Rpemotes hands up is disabled.

**Comment by broonib** [comment]
> -- Hands Up Options HandsupEnabled = false, -- You can disable the handsup here / change the keybind. It is currently set to Y HandsupKeybind = 'Y', -- Get the button string here https://docs.fivem.net/docs/game-references/input-mapper-parameter-ids/keyboard/ HandsupKeybindEnabled = false, HandsupKeybindInCarEnabled = false,
> 
> Is your config set like this?

Hi yes, Ive delete server cache, Ive restarted the server several times. Ive deleted my own cache etc and still getting it, including resetting my keybinds aswell. But as soon as I stop rpemotes resource, Handsup works as it should.

**Comment by broonib** [comment]
No we have them bound to x and no longer work at all lol

**Comment by broonib** [comment]
It maybe a keybind issue, let me get back to you on this apologies

**Comment by alberttheprince** [comment]
> It maybe a keybind issue, let me get back to you on this apologies

sure, just let us know in case this is the issue - helpful for others who experience issue like this

**Comment by alberttheprince** [comment]
Closed as no additional info/context given.
