### ISSUE TITLE
Replacement of props made by TayMcKenzie

### ISSUE THREAD

**Issue by alberttheprince** [alberttheprince/rpemotes-reborn#50]
**Describe the Feature**
This is a general request for anyone to work on replacing objects added to rpemotes by Tay. This should be done in a way that preserves the look of the emotes (especially with respect to LGBTQIA+ emotes, which represent important/useful in the list of emotes. 

**Additional context**
Due to the recent turn to reselling of other's work as his own, it would be best to disassociate as much as possible from Tay.

This is not high priority, as all props are used within the appropriate license rights, but better to get rid of anything associated with bad apples in the community with something higher quality.

**Comment by alberttheprince** [comment]
A new subfolder was made named rpemotesreborn to start this process. 

I am currently replacing props that I can change myself, and replacing the things that were just "Tay branded" base models. Help is appreciated/needed for more advanced props like flags.

https://github.com/alberttheprince/rpemotes-reborn/tree/master/stream/%5BProps%5D/rpemotesreborn

The following are WIP by me (need to get them loaded in as props):

Replacements of these are created, just need to finish models.

![image](https://github.com/user-attachments/assets/c0f3f732-8863-400c-a5e3-533d62dbbb36)

**Comment by alberttheprince** [comment]
Replacing/changing these is beyond my skill level as they use cloth and particle physics. If you know someone or can, please help us out!

If you happen to know the original creator of these, please let me know so I can reach out. Some of these props (like the LSPD badges) are not made by Tay and have just been included for reasons unknown.

![image](https://github.com/user-attachments/assets/caaebe6d-8e1f-441a-bbf7-1e37383e9e05)

**Comment by iSentrie** [comment]
If it's an issue, then why not to just remove it?

**Comment by alberttheprince** [comment]
> If it's an issue, then why not to just remove it?

Not a major issue, I've actually finished all of them except the candle. Talk to the creator of the flags, so we have no issues using them unassociated with Tay as he didn't make them.

More of a just clean up/ehancement.

**Comment by alberttheprince** [comment]
Completed conversion/removal of Tay contribs

**Comment by TayMcKenzieNZ** [comment]
Next time you wanna chat shit, my DMs are open.

**Comment by iSentrie** [comment]
> Next time you wanna chat shit, my DMs are open.

I doubt that anyone wants to chat with you, don't post completely unnecessary posts here.
