### ISSUE TITLE
In some emotes some props are in the wrong position

### ISSUE THREAD

**Issue by NinesChaosu** [alberttheprince/rpemotes-reborn#58]
for example (milk & cookies) emote one plate is in wrong incorrect position also (beer female 4) has beer in the wrong position

**Comment by alberttheprince** [comment]
I'm pretty sure milk and cookies is an emote only available in resold version of rpemotes, nothing we can do to assist yo with that. 

Can you download the latest rpemotes release and let us know? Again, we don't provide support for version sold by resellers, so please download the latest from our github.

**Comment by NinesChaosu** [comment]
1.7.2 i got it from this github

**Comment by NinesChaosu** [comment]
`    ["mnc"] = {
        "anim@heists@box_carry@",
        "idle",
        "Milk & Cookies",
        AnimationOptions = {
            Prop = "m23_2_prop_m32_milkncookies_01a",
            PropBone = 57005, --- Right Wrist
            PropPlacement = {
                0.2150,
                0.1140,
                0.0240,
              -81.9185,
             -176.2526,
              -28.4674
            },
            SecondProp = 'm23_2_prop_m32_milkncookies_01a',
            SecondPropBone = 18905, -- Left Wrist
            SecondPropPlacement = {
                0.2700,
                0.1100,
                0.0350,
              -90.0000,
             -180.0000,
               30.0000
            },
            EmoteLoop = true,
            EmoteMoving = true
        }
    },`

**Comment by alberttheprince** [comment]
> ` ["mnc"] = { "anim@heists@box_carry@", "idle", "Milk & Cookies", AnimationOptions = { Prop = "m23_2_prop_m32_milkncookies_01a", PropBone = 57005, --- Right Wrist PropPlacement = { 0.2150, 0.1140, 0.0240, -81.9185, -176.2526, -28.4674 }, SecondProp = 'm23_2_prop_m32_milkncookies_01a', SecondPropBone = 18905, -- Left Wrist SecondPropPlacement = { 0.2700, 0.1100, 0.0350, -90.0000, -180.0000, 30.0000 }, EmoteLoop = true, EmoteMoving = true } },`

Seems it was a mistake on my side, my local copy didn't have MNC! Sorry about that! Fixed the positioning.

The following fix has been pushed to main branch, we'll release a new version with those fixes + some new emotes.

https://github.com/alberttheprince/rpemotes-reborn/commit/d60030dbef83432e195a6f6c065bd1a6a83b073e
