### ISSUE TITLE
[bug] Emote cancels if you or someone touches you

### ISSUE THREAD

**Issue by iSentrie** [alberttheprince/rpemotes-reborn#59]
**To Reproduce**
Steps to reproduce the behaviour:
1. `e vest` or `e wank` or plenty others (not all)..
2. Run in to someone, or wait till someone touches you'
3. Emote cancels

**Expected behaviour**
Emote shouldn't cancel itself if someone walks very closely to you while waiting in line for food, etc, am I right?

**Comment by iSentrie** [comment]
this behaviour stopped for some reason, might be issue somewhere else

**Comment by iSentrie** [comment]
re-appeared again after resource restart, if someone can, please check this out and let me know if the same happens at your server

**Comment by alberttheprince** [comment]
Could this be something related to the ESX portion of the code? I've read some report about this from before I maintained rpemotes, but could never reproduce it.

Here is with dance5, but I tried with vest and other emotes and didn't have an issue. You're not the only one who experienced this.


This server reported this issue: https://5metrics.dev/server/lj58r4 

back in April:

https://forum.cfx.re/t/free-rpemotes-reborn-a-standalone-emote-system-for-fivem/5219460/30?u=noor_nahas

Video:

https://github.com/user-attachments/assets/02a661d1-b86d-4dc1-95b1-0e614a982005

**Comment by Mathu-lmn** [comment]
Hey the code causing issues might be this one https://github.com/Mathu-lmn/rpemotes-reborn/blob/master/client%2FEmote.lua#L1317
I believe there might be an issue and I'll try to test it asap.

**Comment by Mathu-lmn** [comment]
If the player bumps into a ped while holding a prop for example, the animation cancels but the prop stays

**Comment by iSentrie** [comment]
> If the player bumps into a ped while holding a prop for example, the animation cancels but the prop stays

It replays animation after getting bumped, so it seems that it just need some delay aka Wait(2000) before replaying animation

**Comment by iSentrie** [comment]
That was the goal I guess

https://github.com/user-attachments/assets/90f39f13-140c-4b60-9ead-3964fcb6bef6

**Comment by iSentrie** [comment]
Doesn't seem to work if it gets ragdoll, also loses emote and keeps prop.

https://github.com/user-attachments/assets/c3baac52-3ffd-42ee-9900-3ef8b2c0c1f2

**Comment by Mathu-lmn** [comment]
> > If the player bumps into a ped while holding a prop for example, the animation cancels but the prop stays
> 
> It replays animation after getting bumped, so it seems that it just need some delay aka Wait(2000) before replaying animation

Yeah that was the goal of the code I sent earlier basically, if we got bumped into, replay the animation
