### ISSUE TITLE
Props got stuck in the air with preview and I got the message of male only because the preview

### ISSUE THREAD

**Issue by HideMyFace** [alberttheprince/rpemotes-reborn#6]
**Describe the bug**
While scrolling the menu, I got some props stuck in the air with preview enabled (props with colision) and also the message of male only even not pressing enter. Another thing is some previews not work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable preview of anims on menu.
2. Open the menu and scroll down.

**Expected behaviour**
The props disappearing of screen and the message only appearing when pressing enter.

**Additional context**
None.

**Comment by TayMcKenzieNZ** [comment]
And this is the very reason why you should always thoroughly check things before mindlessly accepting pull request; though I wouldn't expect anything more from someone who clearly isn't a developer and just forks and claims other people's work 😂

Also appears that they haven't bothered to do animal emote previews. Yikes. Broken feature, yet bragging about it publicly. That's not good, Noor.

**Comment by alberttheprince** [comment]
> **Describe the bug** While scrolling the menu, I got some props stuck in the air with preview enabled (props with colision) and also the message of male only even not pressing enter. Another thing is some previews not work.
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
> 1. Enable preview of anims on menu.
> 2. Open the menu and scroll down.
> 
> **Expected behaviour** The props disappearing of screen and the message only appearing when pressing enter.
> 
> **Additional context** None.

Were there any error messages? We'll take a look at this, thanks for the report. Are other players able to see this props or are they client sided only?

**Comment by alberttheprince** [comment]
> And this is the very reason why you should always thoroughly check things before mindlessly accepting pull request; though I wouldn't expect anything more from someone who clearly isn't a developer and just forks and claims other people's work 😂
> 
> Also appears that they haven't bothered to do animal emote previews. Yikes. Broken feature, yet bragging about it publicly. That's not good, Noor.

Please refrain from non-issue related discussions, as spammy responses detract from troubleshooting and improvement.

**Comment by iSentrie** [comment]
https://github.com/user-attachments/assets/def55cbe-15df-468c-8d41-5410ef29a584

**Comment by iSentrie** [comment]
https://github.com/user-attachments/assets/9311883a-a5f4-477b-8e62-e33ac0aadc65

**Comment by iSentrie** [comment]
https://github.com/user-attachments/assets/0095dcd6-8a3a-434e-9f45-6fe1fae193bd

**Comment by enzo2991** [comment]
this only affects the client who is previewing, as the prop is not on the network. 
I'm already looking into how to fix thi

**Comment by iSentrie** [comment]
Haven't looked in to this feature at all, but maybe make an option for a user to toggle it on/off?

**Comment by HideMyFace** [comment]
Yes, you have on config the option. Also, thanks for explaining that only the player who used the menu can see the stuck props.

**Comment by iSentrie** [comment]
I meant togglable in game.

**Comment by alberttheprince** [comment]
Would be a potential move for the future, although I feel it's more appropriate for the preview option to be set by server managers/owners.

**Comment by iSentrie** [comment]
Fixed both both main and clone ped.
https://github.com/user-attachments/assets/338bf6fa-295b-4c5c-a204-466593a241e6
