### ISSUE TITLE
Handsup

### ISSUE THREAD

**Issue by Dejvi1** [alberttheprince/rpemotes-reborn#63]
Hello, could you please add feature for handsup to be up only when holding X not just pressing it ?
Basically when holding(not pressing x to handsup and again x to hands down) X hands would be up.

**Comment by iSentrie** [comment]
Added your request, set `HoldToHandsUp = true` in config and make sure hand up is enabled within keybind.

https://github.com/alberttheprince/rpemotes-reborn/commit/0c42ba1a2398a6b1e550b1b5359b23bf5ca56599

**Comment by Dejvi1** [comment]
Amazing, thank you so much !
