### ISSUE TITLE
SQL binding error

### ISSUE THREAD

**Issue by tcloarec-kryzalid** [alberttheprince/rpemotes-reborn#64]
**Describe the bug**
`Error parsing script @rpemotes-reborn/server/Server.lua in resource rpemotes-reborn: @rpemotes-reborn/server/Server.lua:189: ')' expected near '" WHERE id=@id"'`

**To Reproduce**
Enable SQL saving and reboot the server

**Fix**

I fix that with : 

Replace : `MySQL.Async.execute("UPDATE dpkeybinds SET "..v.." = "" WHERE id=@id", {id = srcid}, function()`
To : `MySQL.Async.execute("UPDATE dpkeybinds SET "..v.." = ? WHERE id=@id", {"", id = srcid}, function()`

**Comment by iSentrie** [comment]
fixed in #67
