### ISSUE TITLE
Current animation

### ISSUE THREAD

**Issue by Dejvi1** [alberttheprince/rpemotes-reborn#65]
Hello, one more time i need to ask you if you could add export for checking current emote.
Main idea is that emote then would be possible to use with emote adjust https://github.com/pixelprecisiondev/pp-adjustanim

They did export in the old rpemotes but reborn version is missing it unfortunately.

**Comment by Mathu-lmn** [comment]
Hi, the IsPlayerInAnim returns the currently played animation or nil if no animation is being played

**Comment by Dejvi1** [comment]
i tried that one but i got message that im not doing any animation, i will try to check it once again.. https://github.com/pixelprecisiondev/rpemotes they did fork on this in emote.lua but i dont really know where to put the locals..

**Comment by Dejvi1** [comment]
elseif GetResourceState('rpemotes') == 'started' then
        
        local data = exports.rpemotes:getCurrentEmote()
        if not data then return end
        local MovementType = cache.vehicle and 51 or 0
        if data.AnimationOptions then
            if data.AnimationOptions.EmoteLoop then
                MovementType = 1
                if data.AnimationOptions.EmoteMoving then
                    MovementType = 51
                end
    
            elseif data.AnimationOptions.EmoteMoving then
                MovementType = 51
            elseif data.AnimationOptions.EmoteMoving == false then
                MovementType = 0
            elseif data.AnimationOptions.EmoteStuck then
                MovementType = 50
            end
    
        else
            MovementType = 0
        end
    
        if InVehicle == 1 then
            MovementType = 51
        end
        if not IsEntityPlayingAnim(cache.ped, data[1], data[2], 3) then return end
        return {
            dict = data[1],
            anim = data[2],
            flag = MovementType,
            command = 'e ' .. data[4]
        }
    end
    
    this is the part which should work for check emote and let adjustment but i just cant find what to put there from the new version

**Comment by iSentrie** [comment]
Someone broke both `exports["rpemotes"]:IsPlayerInAnim()` and `LocalPlayer.state.emote` it now returns last played emote 24/7

**Comment by iSentrie** [comment]
Fixed in https://github.com/alberttheprince/rpemotes-reborn/commit/a4a527e6847a3b129ec981ab90ef4fd8b3b545bf

@Dejvi1 Use `LocalPlayer.state.emote` to retrieve current emote. Report back if it works for you now.

**Comment by alberttheprince** [comment]
Closed as this is already a feature/function.

**Comment by Dejvi1** [comment]
sorry for reopening this ticket. Basically the export is not working for the adjust script. So could i just ask u for a little guide where can i find the part of the code which starting the animation ?
I tried to contact the creator for adjust but he told me to ask you for update or use his 3 years old rpemotes...
I tried hard to find the correct part but i just cant see it..
Thank you for any possible help
https://github.com/pixelprecisiondev/pp-adjustanim  <<this is the script, in config there is the export and when i put yours in there its not working..
![image](https://github.com/user-attachments/assets/7690ee7a-3bc1-423e-a173-fb499f1975a4)

**Comment by iSentrie** [comment]
> sorry for reopening this ticket. Basically the export is not working for the adjust script. So could i just ask u for a little guide where can i find the part of the code which starting the animation ? I tried to contact the creator for adjust but he told me to ask you for update or use his 3 years old rpemotes... I tried hard to find the correct part but i just cant see it.. Thank you for any possible help https://github.com/pixelprecisiondev/pp-adjustanim <<this is the script, in config there is the export and when i put yours in there its not working.. ![image](https://private-user-images.githubusercontent.com/58938630/374402204-7690ee7a-3bc1-423e-a173-fb499f1975a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjEwNjQsIm5iZiI6MTcyODM2MDc2NCwicGF0aCI6Ii81ODkzODYzMC8zNzQ0MDIyMDQtNzY5MGVlN2EtM2JjMS00MjNlLWExNzMtZmI0OTlmMTk3NWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA0MTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTE1YmRlYWQ1MzE3ZmRjNmZjOWRhYzBhNjNkOGU2YjM0N2Q3NmRhMDc0M2VmYzU1NmMyNGJiNGEyNjhmMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uFgoJg0nknmnJ7u-T_XvfvzrqiUju3lwqBR_aYSGh5A)

Our build doesn't support it. It wont work.

**Comment by Dejvi1** [comment]
i see, thank you anyway for the info :)

**Comment by iSentrie** [comment]
> i see, thank you anyway for the info :)

Try now with default pp-adjustanim, I made a PR to support it.

https://github.com/user-attachments/assets/10ab8849-9d54-4ba1-be46-730feaeb28dd

Check and report back if everything is fine.

**Comment by Dejvi1** [comment]
Absolutely amazing !! its working, thank u thank u so so much!! <3 
And just on the fresh install 
![image](https://github.com/user-attachments/assets/13e46628-4b1b-46ed-91ac-f10138d8c27d)
but i guess i just missed some config line .. Thank you once more sir

**Comment by iSentrie** [comment]
> Absolutely amazing !! its working, thank u thank u so so much!! <3 And just on the fresh install ![image](https://private-user-

Your welcome :)
For the error uncomment mysql in fxmanifest
