### ISSUE TITLE
A problem occurred server.lua

### ISSUE THREAD

**Issue by osdaohdph** [alberttheprince/rpemotes-reborn#66]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
A clear and concise description of what you expected to happe
![image](https://github.com/user-attachments/assets/7bba9774-50b6-44b4-a458-b809add0c05f)
n.

**Additional context**
![螢幕擷取畫面 2024-10-05 141943](https://github.com/user-attachments/assets/a488d41e-77be-457a-a454-fadeb9c3099e)

**Comment by iSentrie** [comment]
fixed in #67
