### ISSUE TITLE
Config Option HoldToHandsUp doesn't work

### ISSUE THREAD

**Issue by CptnCat** [alberttheprince/rpemotes-reborn#69]
If you enable the Option ``HoldToHandsUp``, the complete handsup keybind is broken.

**Comment by iSentrie** [comment]
It works on both modes, perfectly fine. You might have "common" fivem keybind bug. Which is unrelated to the script itself.

https://github.com/user-attachments/assets/86979eda-0904-4bd6-9b37-eb9b9125ef2f

Try `unbind keyboard <hands up key>` and then bind it again through settings or `bind keyboard <key> +handsup`

**Comment by iSentrie** [comment]
Closing due to no further response and the script actually works.
