### ISSUE TITLE
Emotebind does not respond to input.

### ISSUE THREAD

**Issue by oXMarloXo** [alberttheprince/rpemotes-reborn#71]
**Describe the bug**
The error can be seen in the picture. 
The Emotebind does not respond to input with the names of the keys.
Apparently num4 doesn't exist.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to chat.
2. Type /emotebind num4 sit.
3. You can see the bug there.

**Expected behaviour**
That it accepts all keybinds and saves the database.

**Comment by oXMarloXo** [comment]
![image](https://github.com/user-attachments/assets/81161fff-4345-4d1f-b40f-8969e7ba7719)

**Comment by iSentrie** [comment]
# Keybinds and SQL 🎛️

To use the SQL features, install the latest version of the [oxmysql](https://github.com/overextended/oxmysql) resource and enable the setting in `config.lua`

```lua
SqlKeybinding = false,
```

If you do not want to use the SQL features keep the `oxmysql` region in fxmanifest.lua commented out.

Alternatively, you can use the keybind command that comes with FiveM without having to use SQL, by entering the following into F8:

`bind keyboard "Yourbutton" "e youremote"`. To remove the keybind, type `"unbind keyboard "Yourbutton"`.

**Comment by oXMarloXo** [comment]
The Sql Keybinding is set to true. 

Sql Keybinding = true, -- If you have the SQL imported enable this to turn on keybinding.

There is a comment in the fxmanifest.lua.

server_script '@oxmysql/lib/MySQL.lua'

The error does not exist on the server.

Because I tested the script with a raw ESX server.

**Comment by alberttheprince** [comment]
> The Sql Keybinding is set to true.
> 
> Sql Keybinding = true, -- If you have the SQL imported enable this to turn on keybinding.
> 
> There is a comment in the fxmanifest.lua.
> 
> server_script '@oxmysql/lib/MySQL.lua'
> 
> The error does not exist on the server.
> 
> Because I tested the script with a raw ESX server.

Did you uncomment it in the fxmanifest? Not understanding what you're saying here.

**Comment by oXMarloXo** [comment]
> > The Sql Keybinding is set to true.
> > Sql Keybinding = true, -- If you have the SQL imported enable this to turn on keybinding.
> > There is a comment in the fxmanifest.lua.
> > server_script '@oxmysql/lib/MySQL.lua'
> > The error does not exist on the server.
> > Because I tested the script with a raw ESX server.
> 
> Did you uncomment it in the fxmanifest? Not understanding what you're saying here.

Yes, it's uncommented.

![image](https://github.com/user-attachments/assets/cdd9e99e-43d8-4727-a486-1cd01b8bbe6c)

And the other one is set to true.

![image](https://github.com/user-attachments/assets/1e5d424b-8a31-43db-a848-8f5883d3f18b)

**Comment by alberttheprince** [comment]
Can you verify which version you're using? Is this release or the main branch?

**Comment by oXMarloXo** [comment]
# rpemotes reborn

fx_version 'cerulean'
game 'gta5'
description 'rpemotes-reborn'
version '1.7.8'


# OXMYSQL

fx_version 'cerulean'
game 'common'
use_experimental_fxv2_oal 'yes'
lua54 'yes'

name 'oxmysql'
author 'Overextended'
version '2.12.0'

**Comment by iSentrie** [comment]
it's deprecated, i dont see any reason to support that feature, use other key bind method I mentioned earlier

**Comment by alberttheprince** [comment]
> it's deprecated, i dont see any reason to support that feature, use other key bind method I mentioned earlier

Oh, so is this just appearing as an unused command? We should check the newest version and update latest.

**Comment by alberttheprince** [comment]
Closing this as method is deprecated in most recent version.
