### ISSUE TITLE
Emoting/Crouching/Crawling while inventory is open

### ISSUE THREAD

**Issue by SirOMGitsYOU** [alberttheprince/rpemotes-reborn#72]
I am using Ox Inventory, If you control click Items it quick swaps the container they are in. Currently with RP Emotes reborn this also crouches or crawls you at the same time, Is there any way an option can be added to prevent crouch/crawling or emoting while your inventory is open?

**Comment by alberttheprince** [comment]
I use ox_inventory as well and this isn't something I've experienced. 

What version of rpemotes are you using?

**Comment by alberttheprince** [comment]
Closed as no response given

**Comment by SirOMGitsYOU** [comment]
version '1.7.8'

Uploaded a video for you to see what I mean, https://streamable.com/iuzwso

**Comment by iSentrie** [comment]
> version '1.7.8'
> 
> Uploaded a video for you to see what I mean, https://streamable.com/iuzwso

That doesn't happen for me. Looks like you made plenty of modifications to inventory, that might be the cause of that.
