### ISSUE TITLE
Menu stops scrolling in prop emotes

### ISSUE THREAD

**Issue by Ell34** [alberttheprince/rpemotes-reborn#75]
Myself and players have noticed an issue when in the prop emotes section. Scrolling is a bit laggy and then all of the sudden you cannot scroll any further.

**Comment by alberttheprince** [comment]
Which emote does this happen on? This is usually due to a broken emote. Due to props, config, missing anim files, etc.

**Comment by alberttheprince** [comment]
Closed due to no response
