### ISSUE TITLE
fxmanifest.lua version does not match the GitHub release version

### ISSUE THREAD

**Issue by jonjongames1997** [alberttheprince/rpemotes-reborn#76]
I updated this to 1.8.0 but the txadmin console log is saying that its still outdated on 1.7.8, I checked the fxmanifest.lua, it shows 1.7.8 as the version instead of 1.8.0.

**Comment by iSentrie** [comment]
then you didn't updated

**Comment by alberttheprince** [comment]
Will update this 1.8.1, should just be a single print atm.
